config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get '/repos', to: 'githubdetails#repos'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#new'
  resources :votes, only: %i[index create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base

  USER_LIST = ['huzefahuzu']
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord

  def self.totals
    [Vote.where(color: 'red').count, Vote.where(color: 'blue').count]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end
end

app/controllers/githubdetails_controller.rb
class GithubdetailsController < ApplicationController

  def repos
    github = Github.new(user: User::USER_LIST.first)
    @repos_list = github.repos.list.body
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.from_omniauth(request.env['omniauth.auth'])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
    @votes = Vote.totals

    respond_to do |format|
      format.html
      format.json { render json: @votes }
    end
  end

  def create
    Vote.create(vote_params)
    @votes = Vote.totals
    respond_to do |format|
      format.js
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# sessions helper
module SessionsHelper
end

app/views/githubdetails/repos.html.erb
<% @repos_list.each do |repo| %>
  <p>Name: <%= repo["name"]%></p>  
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubDetails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/votes/create.js.erb
$("#red-count").html("<%= @votes[0] %>");
$("#blue-count").html("<%= @votes[1] %>");
updateData();

app/views/votes/index.html.erb
<div class="main-container">
  <h1>Red vs. Blue</h1>
  
  <div id="vote-counter">
    <h3>Vote count</h3> 
    <p>Red: <span id="red-count"><%= @votes[0] %></span></p>
    <p>Blue: <span id="blue-count"><%= @votes[1] %></span></p>
  </div>

  <div id="voting-box">
    <%= link_to 'Vote Red', votes_path(vote: {color: 'red'}), {remote: true, method: :post, class: 'vote-button red' } %>
    <%= link_to 'Vote Blue', votes_path(vote: {color: 'blue'}), {remote: true, method: :post, class: 'vote-button blue' } %>
  </div>
</div>

<div id="plot-container">
  <svg id="plot"></svg>
</div>